name: quiz_master
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^4.7.0
  firebase_auth: ^6.4.0
  cloud_firestore: ^6.3.0
  flutter_dotenv: ^6.0.1
  provider: ^6.1.2
  file_picker: ^8.0.0
  syncfusion_flutter_pdf: ^33.2.5
  http: ^1.6.0
  html: ^0.15.6
  image_picker: ^1.2.2
  firebase_storage: ^13.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.0
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - .env

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/logo.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/logo.png"

flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/logo.png"
  android: true
  ios: false
  android_12:
    color: "#FFFFFF"
    image: "assets/logo.png"
